# Generated by Django 4.1.2 on 2022-10-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_key', models.CharField(max_length=255, verbose_name='secure key')),
            ],
            options={
                'verbose_name': 'server key',
                'verbose_name_plural': 'server keys',
            },
        ),
        migrations.CreateModel(
            name='LoginCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='user name')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('file', models.FileField(blank=True, null=True, upload_to='cookie', verbose_name='فایل کوکی')),
                ('cookie', models.BinaryField(verbose_name='اطلاعات کوکی')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name="cookie's saving time")),
            ],
            options={
                'verbose_name': "login's cookie",
                'verbose_name_plural': "login's cookies",
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pure_image', models.ImageField(upload_to='snapshot', verbose_name='image')),
                ('watermarked_image', models.ImageField(blank=True, null=True, upload_to='snapshot_watermarked', verbose_name='watermarked image')),
            ],
            options={
                'verbose_name': 'image gallery',
                'verbose_name_plural': 'image gallery',
            },
        ),
        migrations.CreateModel(
            name='TelegramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255, verbose_name='bot token')),
                ('channel_name', models.CharField(max_length=255, verbose_name='channel name')),
            ],
            options={
                'verbose_name': 'telegram setting',
                'verbose_name_plural': 'telegram settings',
            },
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark', models.ImageField(upload_to='watermark', verbose_name='watermark')),
            ],
            options={
                'verbose_name': 'watermark',
                'verbose_name_plural': 'watermarks',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tradingview.watermark', verbose_name='watermark')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
