# Generated by Django 4.1.2 on 2022-10-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingview', '0002_remove_logincookie_cookie_remove_logincookie_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snapshot',
        ),
        migrations.AlterModelOptions(
            name='key',
            options={'verbose_name': 'Webhook secure key', 'verbose_name_plural': 'Webhook secure keys'},
        ),
        migrations.AlterModelOptions(
            name='telegramsetting',
            options={'verbose_name': 'channel and robot', 'verbose_name_plural': 'channels and robots'},
        ),
    ]
